### PR TITLE
fixed the broken link of polygon academy

### PR DESCRIPTION
**Pull request by nirban256**
## Related Issue

- Information about the related issue

Closes: #50 

### Describe the changes you've made

Changed the previous link by the Polygon academy link.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Documentation update.

## Checklist

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

 
## Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/WebXDAO/.github/blob/main/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by nirban256** [comment]
@mkubdev  review the changes once

**Comment by nirban256** [comment]
> Looks good. Thanks! 🎉

welcome. Looking forward to contribute more in the project ☺

**Comment by nirban256** [comment]
> Looks good. Thanks! 🎉

won't you merge the pr?

**Review by shuklaritvik06 — APPROVED** [review]
LGTM

**Comment by shuklaritvik06** [comment]
> > Looks good. Thanks! 🎉
> 
> won't you merge the pr?

Merged :) thank you for contributing!

**Pull request merged**
