### PR TITLE
Fix: typos

### PR DESCRIPTION
**Pull request by omahs**
Fix: typos

### CODE REVIEW

**Review by mkubdev — APPROVED** [review]
Hi @omahs 👋 Thanks a lot for your PR!
Everything look good to me 🚀

**Review by KukretiShubham — APPROVED** [review]
Good work, thanks for your contribution

**Review by shuklaritvik06 — APPROVED** [review]
LGTM

**Review by vinzvinci — COMMENTED** [review]
Awesome! Thanks for fast review!

**Pull request merged**
